export const cityWeatherBlockPositionData = [
    { name: "宜蘭縣", calX: +10, calY: 0 },
    { name: "基隆市", calX: 0, calY: -50 },
    { name: "新北市", calX: +35, calY: -20 },
    { name: "臺北市", calX: -70, calY: -60 },
    { name: "桃園市", calX: -105, calY: -73 },
    { name: "新竹縣", calX: 0, calY: -5 },
    { name: "新竹市", calX: -90, calY: -45 },
    { name: "苗栗縣", calX: -100, calY: -50 },
    { name: "臺中市", calX: -140, calY: -40 },
    { name: "彰化縣", calX: -100, calY: -40 },
    { name: "南投縣", calX: -20, calY: -20 },
    { name: "雲林縣", calX: -100, calY: -30 },
    { name: "嘉義縣", calX: -140, calY: -10 },
    { name: "嘉義市", calX: 10, calY: -20 },
    { name: "臺南市", calX: -90, calY: 0 },
    { name: "高雄市", calX: -125, calY: +25 },
    { name: "屏東縣", calX: -100, calY: 0 },
    { name: "花蓮縣", calX: +25, calY: 0 },
    { name: "臺東縣", calX: +15, calY: -10 },
    { name: "澎湖縣", calX: -100, calY: 0 },
    { name: "金門縣", calX: -10, calY: 0 },
    { name: "連江縣", calX: -10, calY: 0 }
];